version: '3.8'

services:
  backend:
    image: ghcr.io/mgaldon17/task-management-app-be:latest
    ports:
      - "8080:8080"
    environment:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: ["sh", "-c", "echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin"]
    networks:
      - app-network

  frontend:
    image: ghcr.io/mgaldon17/task-management-app-fe:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    command: [ "sh", "-c", "echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
